name: Build with Maven

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use for building'
        required: false
        type: string
        default: '17'
      java-distribution:
        description: 'Java distribution to use for building'
        required: false
        type: string
        default: 'temurin'
      maven-args:
        description: 'Additional arguments to pass to maven'
        required: false
        type: string
        default: ''
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set settings
        uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-set-settings.yml@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
        secrets:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      
      - name: Build with Maven
        run: 'mvn --batch-mode --update-snapshots clean verify ${{ inputs.maven-args }}'
