name: Publish artifact(s) to the Mekom Nexus Repository

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version to use for publishing'
        required: false
        type: string
        default: '17'
      java-distribution:
        description: 'Java distribution to use for publishing'
        required: false
        type: string
        default: 'temurin'
      maven-args:
        description: 'Additional arguments to pass to maven'
        required: false
        type: string
        default: '-DskipTests=true'
    secrets:
      NEXUS_USERNAME:
        required: true
      NEXUS_PASSWORD:
        required: true


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set settings
        uses: mekomsolutions/shared-github-workflow/.github/workflows/maven-set-settings.yml@main
        with:
          java-version: ${{ inputs.java-version }}
          java-distribution: ${{ inputs.java-distribution }}
          nexus-username: ${{ secrets.NEXUS_USERNAME }}
          nexus-password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Publish maven artifacts
        run: 'mvn --batch-mode clean deploy ${{ inputs.maven-args }}'
